### PR TITLE
Dot product 

### PR DESCRIPTION
**Pull request by herkura**
I have created the file and added the changes, If still anything is required from my side just ping me 😄

### CODE REVIEW

**Comment by thesprydatasnake** [comment]
@herkura Sweet! Please add your name in contributing.md too.

**Comment by herkura** [comment]
there is no such file named as contributors.md. Should I create one?

**Comment by thesprydatasnake** [comment]
I think it was created after you forked 🥇 No worries, I'll merge and add you there.

**Comment by thesprydatasnake** [comment]
@herkura 
Congrats on the merged PR!
All the successful participants will be shown up on our Youtube Channel here: https://www.youtube.com/channel/UCbg7VWFFDjSUD5XxKx4qGcQ/about
Subscibe and turn on notifications! And Leave a star here if you like!

**Comment by herkura** [comment]
@thesprydatasnake thx a lot!! 👍🏻 😄

**Comment by herkura** [comment]
@thesprydatasnake I guess you can add this on hacktoberfest 2021

**Pull request merged**
